In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

# two dimensional array 
## (notice number of square brackets)

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
# note that it must be a tuple for multiple dimensions
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random number from standard distribution from 0 to 1

In [18]:
np.random.rand(5)

array([0.42570105, 0.78701989, 0.41362395, 0.95643079, 0.95187466])

In [21]:
# note that you don't need a tuple here
np.random.rand(5,5)

array([[0.43479692, 0.33349699, 0.15247109, 0.44345477, 0.34900753],
       [0.96190517, 0.98260743, 0.09874943, 0.7441008 , 0.22352095],
       [0.24974331, 0.61496841, 0.50607077, 0.98419987, 0.32262923],
       [0.69134429, 0.4817837 , 0.23924606, 0.70150719, 0.70553671],
       [0.12046119, 0.1643478 , 0.27758977, 0.32221967, 0.07687854]])

# distribution centred around 0

In [22]:
np.random.randn(2)

array([0.02160747, 0.41187775])

In [23]:
np.random.randn(3,2)

array([[ 0.10385577, -0.35254293],
       [ 1.01212011,  0.59908494],
       [-0.09180248, -0.04192336]])

In [25]:
# inclusive,exlcusive
np.random.randint(1,100)

64

In [26]:
np.random.randint(1,100,5)

array([75,  7, 66, 86, 59])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([38, 42,  5, 12, 39, 44,  2, 11, 14, 49])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

49

In [33]:
ranarr.min()

2

In [34]:
ranarr.argmax()

9

In [35]:
ranarr.argmin()

6

In [37]:
arr.shape

(25,)

In [38]:
arr.dtype

dtype('int64')

# indexing and selection

In [39]:
arr = np.arange(0,10)

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[8]

8

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
arr[5:]

array([5, 6, 7, 8, 9])

In [46]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
 arr[:3] = 100

In [48]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [49]:
slice_of_array = arr[3:6]

In [50]:
slice_of_array

array([3, 4, 5])

In [51]:
slice_of_array[:] = 69

In [52]:
slice_of_array

array([69, 69, 69])

In [53]:
arr

array([100, 100, 100,  69,  69,  69,   6,   7,   8,   9])

## Note that if you broadcast on a slice of an array you will be changing the original array as well. to not do this, be sure to use .copy() to make a true copy of an array and not just a view.

In [54]:
arr_copy = arr.copy()

In [55]:
arr_copy

array([100, 100, 100,  69,  69,  69,   6,   7,   8,   9])

In [56]:
arr_copy[:] = 20

In [57]:
arr_copy

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [58]:
arr

array([100, 100, 100,  69,  69,  69,   6,   7,   8,   9])

# 2-D arrays

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [60]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [61]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d[0]

array([ 5, 10, 15])

In [63]:
arr_2d[0][0]

5

In [64]:
arr_2d[2][1]

40

## grab rows or columns by using double brackets. you can even grab out of order

In [90]:
arr_2d[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [91]:
arr_2d[[2,0]]

array([[35, 40, 45],
       [ 5, 10, 15]])

### single bracket notation recommended

In [65]:
arr_2d[1,2]

30

## slice of matrices

In [66]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [67]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [70]:
arr_2d[:3,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

# conditional selection

In [71]:
arr = np.arange(0,11)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [74]:
bool_arr = arr > 5

In [75]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [76]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [77]:
arr[arr<3]

array([0, 1, 2])

# Numpy operations

In [78]:
arr = np.arange(0,11)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [81]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [83]:
arr / arr

/Users/williamacosta/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [84]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [85]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [86]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [87]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [88]:
np.log(arr)

/Users/williamacosta/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])